// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://owmvufqrxcymnkrjexls.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im93bXZ1ZnFyeGN5bW5rcmpleGxzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4OTU4MzcsImV4cCI6MjA2NzQ3MTgzN30.Ee2h20OrGQEsK9OMk8-L0Gy0xoXE0Jr0_e5RhF5pkBE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});